### ISSUE TITLE
Large gap at the end of the graph

### ISSUE THREAD

**Issue by khaytsus** [solsticedhiver/rtl_heatmap#3]
Look at the attachment in #2, there's a large gap with no ticks etc at the far right of the graph.  I think there is data there, so maybe it's not scaling the ticks at all the way to the end?  Not sure.

**Comment by solsticedhiver** [comment]
This is because that -beep- *rtl_power* output incorrect data in `.csv` file.
Specifically, in your data set, there is 2 extra numbers for each line that should not be there.

I need to improve the parsing of the csv file to double check everything because my naive way of doing it is not enough
