### ISSUE TITLE
local variable 'axis' referenced before assignment

### ISSUE THREAD

**Issue by SDRWaveRunner** [solsticedhiver/rtl_heatmap#4]
When using rtl_heatmap without the option --xlines and --xlines , the var xargs near lines 293-299 is not set and python complaines about an unreferenced var.
This can be solved when checking if the var "axis" is set in the if-statement:

```    # show lines matching major ticks
    if args.xlines:
        axis = 'x'
    if args.ylines:
        axis = 'y'
    if args.xlines and args.ylines:
        axis = 'both'
    else:
        axis = 'none'
    ax.grid(True, axis=axis, which='major', color='white', linewidth=1, linestyle='-.', zorder=10, alpha=0.5)```

**Comment by solsticedhiver** [comment]
Thank your for the bug report. This should be fixed now
